version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - ./.env
    ports:
      - 5432:5432

  backend:
    env_file:
      - ./.env
    build:
      context: ./Backend
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
    ports:
      - 80:80
